import { describe, expect, it } from "vitest";
import { buildTopicMasterySummary, defaultUserSettings, emptyNotes, normalizeMilestone, normalizeProgress, normalizeSettings, reflectionIsComplete, validateUserSettings } from "../lib/types";
describe("runtime data constraints", () => {
  it("normalizes progress fields to the contract", () => { const value = normalizeProgress({ weekId: "week-1", confidence: 99, minutes: -3, notes: { ...emptyNotes, evidence: "e" } }); expect(value.confidence).toBe(5); expect(value.minutes).toBe(0); expect(value.notes.evidence).toBe("e"); expect(value.createdAt).toBeTruthy(); expect(value.updatedAt).toBeTruthy(); });
  it("derives milestone total and bounds rubric scores", () => { const value = normalizeMilestone({ checkpointId: "week-4", closedLoop: 2, vocabulary: 2, diagnosis: 2, modelEvaluation: 2, deployment: 2, conversation: 2 }); expect(value.total).toBe(12); expect(normalizeMilestone({ checkpointId: "week-8", closedLoop: 8 }).closedLoop).toBe(2); });
  it("rejects non-Friday setup dates", () => { expect(validateUserSettings({ firstFriday: "2026-09-05", timezone: "America/Los_Angeles", onboardingStatus: "not_started" })).toContain("First Friday must be a valid Friday date."); });
  it("normalizes new account defaults and reflection completion", () => { const settings = normalizeSettings({ firstFriday: null, timezone: "America/Los_Angeles", onboardingStatus: "not_started" }); expect(settings).toMatchObject(defaultUserSettings); expect(reflectionIsComplete({ activityId: "w1-f1", explanation: "A loop", unclear: "Timing", scratchNotes: "", updatedAt: "now" })).toBe(true); });
  it("uses the latest distinct valid quiz evaluation and rejects duplicate exploits", () => { const base = { weekId: "week-1", answer: "answer", createdAt: "2026-01-01", updatedAt: "2026-01-01" }; const make = (id: string, score: number, at: string) => ({ ...base, id: `${id}-${at}`, questionId: id, createdAt: at, updatedAt: at, evaluation: { id: `e-${id}-${at}`, questionId: id, accuracy: score, causalReasoning: score, simplicity: score, transfer: score, feedback: "ok", misconceptions: [], nextRevisionPrompt: "revise", model: "mock", createdAt: at } }); const attempts = [make("w1-q1", 0, "2026-01-01"), make("w1-q1", 3, "2026-01-02"), make("w1-q2", 3, "2026-01-02"), make("w1-q3", 3, "2026-01-02")]; const summary = buildTopicMasterySummary("week-1", ["w1-q1", "w1-q2", "w1-q3", "w1-q4"], attempts); expect(summary.score).toBe(12); expect(summary.completedQuestionIds).toEqual(expect.arrayContaining(["w1-q1", "w1-q2", "w1-q3"])); expect(summary.passed).toBe(false); });
});
