import { curriculum } from "./curriculum";
import { MilestoneScore, QuizAttempt, UserSettings, WeekProgress } from "./types";

export const EXPORT_SCHEMA_VERSION = "2.0";
export type ExportPayload = { schema: "robotics-learning-tracker"; version: string; exportedAt: string; settings: UserSettings; preferences: Pick<UserSettings, "weeklyGoalMinutes" | "aiFeedbackEnabled" | "aiConsentAt" | "quizDifficulty" | "feedbackDepth">; weeks: Record<string, WeekProgress>; milestones: Record<string, MilestoneScore>; attempts: Record<string, QuizAttempt>; evaluations: Record<string, NonNullable<QuizAttempt["evaluation"]>>; revisions: QuizAttempt[]; challenges: QuizAttempt[] };
export function buildExportPayload(settings: UserSettings, weeks: Record<string, WeekProgress>, milestones: Record<string, MilestoneScore>, attempts: Record<string, QuizAttempt> = {}): ExportPayload { const values = Object.values(attempts); return { schema: "robotics-learning-tracker", version: EXPORT_SCHEMA_VERSION, exportedAt: new Date().toISOString(), settings, preferences: { weeklyGoalMinutes: settings.weeklyGoalMinutes ?? 420, aiFeedbackEnabled: settings.aiFeedbackEnabled ?? false, aiConsentAt: settings.aiConsentAt ?? null, quizDifficulty: settings.quizDifficulty ?? "conversation-ready", feedbackDepth: settings.feedbackDepth ?? "standard" }, weeks, milestones, attempts, evaluations: Object.fromEntries(values.filter((item) => item.evaluation).map((item) => [item.evaluation!.id, item.evaluation!])), revisions: values.filter((item) => Boolean(item.revisionOf)), challenges: values.filter((item) => Boolean(item.challenged)) }; }
const value = (text: string | number | boolean | null | undefined) => text === null || text === undefined || text === "" ? "_Not written yet._" : String(text);
export function markdownExport(settings: UserSettings, progress: Record<string, WeekProgress>, milestones: Record<string, MilestoneScore> = {}): string {
  const weeks = curriculum.map((week) => { const item = progress[week.id]; const notes = item?.notes; const milestone = milestones[`week-${week.number}`]; const reflections = Object.values(item?.reflections ?? {}).map((reflection) => `\n### Lesson reflection · ${reflection.activityId}\n- Explanation: ${value(reflection.explanation)}\n- Unclear: ${value(reflection.unclear)}\n- Scratch notes: ${value(reflection.scratchNotes)}`).join("\n"); const mastery = item?.mastery ? `\n### Topic mastery\n- Score: ${item.mastery.score}/12\n- Passed: ${item.mastery.passed ? "yes" : "revision needed"}\n- Misconceptions: ${value(item.mastery.misconceptions.join("; "))}` : ""; const milestoneBlock = [4, 8, 12].includes(week.number) ? `\n### Milestone score\n- Closed-loop explanation: ${value(milestone?.closedLoop)}\n- Technical vocabulary: ${value(milestone?.vocabulary)}\n- Failure diagnosis: ${value(milestone?.diagnosis)}\n- Model evaluation: ${value(milestone?.modelEvaluation)}\n- Deployment judgment: ${value(milestone?.deployment)}\n- Conversation quality: ${value(milestone?.conversation)}\n- Total: ${milestone ? `${milestone.total}/12` : "—/12"}\n- Notes: ${value(milestone?.notes)}\n- Completion date: ${value(milestone?.completionDate)}\n` : ""; return `## Week ${week.number} — ${week.title}\n\n- Summary: ${value(week.summary)}\n- Objective: ${value(week.objective)}\n- Tags: ${value(week.tags?.join(", "))}\n- Friday complete: ${item?.fridayComplete ? "yes" : "no"}\n- Saturday complete: ${item?.saturdayComplete ? "yes" : "no"}\n- Brief complete: ${item?.briefComplete ? "yes" : "no"}\n- Activities: ${item?.completedActivityIds.length ?? 0}\n- Confidence: ${item?.confidence ?? "—"}/5\n- Time: ${item?.minutes ?? "—"} minutes\n\n### Mechanism\n${value(notes?.mechanism)}\n\n### Loop position\n${value(notes?.loopPosition)}\n\n### Tradeoff\n${value(notes?.tradeoff)}\n\n### Evidence\n${value(notes?.evidence)}\n\n### Failure mode\n${value(notes?.failureMode)}\n\n### Business implication\n${value(notes?.businessImplication)}\n\n### Founder question\n${value(notes?.founderQuestion)}\n\n### Engineer question\n${value(notes?.engineerQuestion)}\n\n### Investor question\n${value(notes?.investorQuestion)}\n\n### Two-minute explanation\n${value(notes?.twoMinuteExplanation)}\n\n### Gaps\n${value(notes?.gaps)}\n\n### Retrieval prompt\n${value(notes?.retrievalPrompt)}\n\n### Biggest question\n${value(item?.biggestQuestion)}${reflections}${mastery}${milestoneBlock}`; }).join("\n"); return `# Robotics and Physical AI — Learning Log\n\n- Schema: ${EXPORT_SCHEMA_VERSION}\n- First Friday: ${settings.firstFriday ?? "not set"}\n- Timezone: ${settings.timezone}\n- Onboarding: ${settings.onboardingStatus}\n- Weekly target: ${settings.weeklyGoalMinutes ?? 420} minutes\n- AI evaluation: ${settings.aiFeedbackEnabled ? "enabled with consent" : "disabled"}\n\n${weeks}`;
}
