import { curriculum } from "./curriculum";
import { MilestoneScore, UserSettings, WeekProgress } from "./types";
export const EXPORT_SCHEMA_VERSION = "1.0";
export type ExportPayload = { schema: "robotics-learning-tracker"; version: string; exportedAt: string; settings: UserSettings; weeks: Record<string, WeekProgress>; milestones: Record<string, MilestoneScore> };
export function buildExportPayload(settings: UserSettings, weeks: Record<string, WeekProgress>, milestones: Record<string, MilestoneScore>): ExportPayload { return { schema: "robotics-learning-tracker", version: EXPORT_SCHEMA_VERSION, exportedAt: new Date().toISOString(), settings, weeks, milestones }; }
const value = (text: string | number | boolean | null | undefined) => text === null || text === undefined || text === "" ? "_Not written yet._" : String(text);
export function markdownExport(settings: UserSettings, progress: Record<string, WeekProgress>, milestones: Record<string, MilestoneScore> = {}): string {
  const weeks = curriculum.map((week) => { const item = progress[week.id]; const notes = item?.notes; const milestone = milestones[`week-${week.number}`]; const isMilestoneWeek = [4, 8, 12].includes(week.number); const milestoneBlock = isMilestoneWeek ? `\n### Milestone score\n- Closed-loop explanation: ${value(milestone?.closedLoop)}\n- Technical vocabulary: ${value(milestone?.vocabulary)}\n- Failure diagnosis: ${value(milestone?.diagnosis)}\n- Model evaluation: ${value(milestone?.modelEvaluation)}\n- Deployment judgment: ${value(milestone?.deployment)}\n- Conversation quality: ${value(milestone?.conversation)}\n- Total: ${milestone ? `${milestone.total}/12` : "—/12"}\n- Notes: ${value(milestone?.notes)}\n- Completion date: ${value(milestone?.completionDate)}\n` : ""; return `## Week ${week.number} — ${week.title}\n\n- Friday complete: ${item?.fridayComplete ? "yes" : "no"}\n- Saturday complete: ${item?.saturdayComplete ? "yes" : "no"}\n- Brief complete: ${item?.briefComplete ? "yes" : "no"}\n- Activities: ${item?.completedActivityIds.length ?? 0}\n- Confidence: ${item?.confidence ?? "—"}/5\n- Time: ${item?.minutes ?? "—"} minutes\n\n### Mechanism\n${value(notes?.mechanism)}\n\n### Loop position\n${value(notes?.loopPosition)}\n\n### Tradeoff\n${value(notes?.tradeoff)}\n\n### Evidence\n${value(notes?.evidence)}\n\n### Failure mode\n${value(notes?.failureMode)}\n\n### Business implication\n${value(notes?.businessImplication)}\n\n### Founder question\n${value(notes?.founderQuestion)}\n\n### Engineer question\n${value(notes?.engineerQuestion)}\n\n### Investor question\n${value(notes?.investorQuestion)}\n\n### Two-minute explanation\n${value(notes?.twoMinuteExplanation)}\n\n### Gaps\n${value(notes?.gaps)}\n\n### Retrieval prompt\n${value(notes?.retrievalPrompt)}\n\n### Biggest question\n${value(item?.biggestQuestion)}\n${milestoneBlock}`; }).join("\n"); return `# Robotics and Physical AI — Learning Log\n\n- Schema: ${EXPORT_SCHEMA_VERSION}\n- First Friday: ${settings.firstFriday ?? "not set"}\n- Timezone: ${settings.timezone}\n- Onboarding: ${settings.onboardingStatus}\n\n${weeks}`;
}
